#Finding a Motif in DNA
#= s = "GATATATGCATATACTT"
t = "ATAT" =#

s = "GGCGACTCAGTCGGTCAGTCGGGACCTCAGTCGACGGTTCAGTCGAAGATGTCAGTCGTCAGTCGATCAGTCGTCAGTCGTCAGTCGACTCTCAGTCGCTCAGTCGATCAGTCGGTCAGTCGCGATTGGTTCAGTCGTCAGTCGTCAGTCGTCACGTCAGTCGCTCAGTCGTCAGTCGACCGTCAGTCGTCAGTCGGACGAGTTCAGTCGTCAGTCGCTCAGTCGTCAGTCGCTTCACACAGTCAAGGGTCAGTCGGTCATCAGTCGACACGCTTCAGTCGTCAGTCGAGATCAGTCGGCATTCAGTCGCTGGGTTAAGACGTCTCAGTCGTCTTCAGTCGTCAGTCGCATCAGTCGACTTCAATTAATCAGTCGACTTTCAGTCGTATTCAGTCGTCAGTCGGTCAGTCGTTCAGTCGGATCCGTTCTCCGGTCAGTCGCTCAGTCGGTTTATTCAGTCGTCAGTCGTCATTCATCAGTCGTCAGTCGAACGCATCAGTCGTCAGTCGGTCAGTCGAATCAGTCGCGTCAGTCGATCAGTCGCTTCTCAGTCGTTGTAACCTCAGTCGATCTCAGTCGGATCAGTCGTCAGTCGGTCAGTCGTCAGTCGATCAGTCGATCAGTCGCGATTATCAGTCGAATTCAGTCGGCCCTCAGTCGAATCAGTCGATCAGTCGTCAGTCGTCAGTCGTCAGTCGGCAATCAGTCGCGCTCAGTCGGCTTCAGTCGGGGATCAGTCGTGTTCAGTCGTCAGTCGAAAGTCAGTCGCACTCAGTCGGTAATCAGTCGCTGTTCAGTCGTCAGTCGTGTCAGTCGCGTCAGTCGTCAGTCGTCAGTCGCTCAGTCGGCTTACTCAGTCGCCCTCTCCTCAGTCGAGTTCAGTCGGTGTATCAGTCGGAGAT"
t = "TCAGTCGTC"
function findMotifDNA(s, t)
    i = 1
    finish = false
    position = ""
    while (i <= length(s)) && (!finish)
       if !isnothing(findnext(t, s, i))
            position = position * " " * string(findnext(t, s, i)[1])
            i = findnext(t, s, i)[1] + 1
       else
            finish = true
       end
    end
    println(position)
end

findMotifDNA(s, t)