#= Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do 
not exceed four million, find the sum of the even-valued terms. =#

function evenFibonacciSum(limite)
    a = 1
    b = 2
    
    suma = 1
    while b < limite
        c = a + b
        a = b
        
        if c % 2 == 0
            suma = suma + c
        end

        b = c
    end

    return suma
end

limite = 4000000
println(evenFibonacciSum(limite))